- hosts: localhost
  become: yes
  tasks:
    - name: Connect to my cluster
      shell: gcloud container clusters get-credentials cluster --zone us-east4-b --project iti-sherif

    - name: Create jenkins namespace
      shell: kubectl create namespace jenkins

    - name: Deploy jenkins & lb servies
      command: kubectl apply -f /home/sherifessamahmed/repo/jenkins/
      